//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by pe32smvw.rc

#define IDS_USAGE_STRING							101
#define IDS_VERSION_STRING							102
#define IDS_UNDERADMIN_STRING						103
#define IDS_ELEVATED_STRING							104
#define IDS_IMG_SIGNATURE_DATETIME					105
#define IDS_IMG_FILE_SIGNER							106
#define IDS_IMG_FILE_SIGNERS						107
#define IDS_IMG_TIMESTAMP_DATETIME					108
#define IDS_IMG_TIMESTAMP_SIGNER					109
#define IDS_IMG_TIMESTAMP_SIGNERS					110
#define IDS_IMG_NOT_32BIT							111
#define IDS_MSG_VERBOSE								112
#define IDS_MSG_ADD_SECTION							113

#define IDS_MSG_ADD_SECTION_NAME_SIZE				114
#define IDS_MSG_ADD_SECTION_NAME_SIZE_P				115
#define IDS_MSG_SECTION_NAME_TRUNCATED				116
#define IDS_MSG_FILE_SECTION_NAME_TRUNCATED			117

#define IDS_MSG_ADD_ON_SIGNED						118

#define IDS_ERROR_UNABLE_CREATE_DSA					119
#define IDS_ERROR_FILE_ISNT_FOUND					120
#define IDS_ERROR_INVALID_OPT_KEY					121
#define IDS_ERROR_UNABLE_PROC_ARGS					122
#define IDS_ERROR_SYSTEM							123
#define IDS_MSG_FILE_SIGNED							124
#define IDS_MSG_FILE_BAD_SIG						125
#define IDS_MSG_FILE_SIG_PROV_UNK					126
#define IDS_MSG_FILE_SIG_NOT_TRUSTED				127
#define IDS_MSG_FILE_SIG_ERROR						128
#define IDS_MSG_FILE_SIG_OK							129
#define IDS_MSG_FILE_ACCESS_DENIED					130
#define IDS_MSG_SECT_FORMAT							131
#define IDS_MSG_SECT_FORMAT_VIRTUAL					132
#define IDS_MSG_SECT_FORMAT_HEADER					133
#define IDS_MSG_SECT_MAPPINGS_HEADER				134
#define IDS_MSG_SECT_NOT_FOUND						135
#define IDS_MSG_SECT_FILE_ACCESS_DENIED				136
#define IDS_MSG_ADD_FILE							137
#define IDS_MSG_ADD_FILE_NAME						138
#define IDS_MSG_DOS_HDR_INVALID						139
#define IDS_MSG_NT_PE_INVALID						142
#define IDS_MSG_TARGER_SECTION						143

#define IDS_ERROR_NO_EMPTY_SECTION_DESCRIPTOR		144
#define IDS_MSG_SECTION_NAME_GENERATED				145
#define IDS_MSG_TAG_VALUE							146
#define IDS_ERROR_UNABLE_GENERATE_SECTION_NAME		147

#define IDS_MSG_OPT_HDR_PTRS_MAP					148
#define IDS_MSG_DATA_DIRS_MAP						149

#define IDS_MSG_ADD_SECTION_SIZE					150
#define IDS_MSG_ADD_SECTION_SIZE_P					151
#define IDS_MSG_ADD_DATA_SECTION_NAME				152

#define IDS_MSG_ADD_VIRTUAL_SECT_START				153
#define IDS_MSG_ADD_DATA_SECT_START					154

#define IDS_MSG_DATA_SECTION_NAME_GENERATED			155
#define IDS_ERROR_SECTION_EXISTS					156

#define IDS_MSG_IMG_OPT_HDR_ENTRY_POINT				178
#define IDS_MSG_IMG_OPT_HDR_CODE_BASE				179
#define IDS_MSG_IMG_OPT_HDR_DATA_BASE				180

#define IDS_MSG_DATADIR_EXPORTS						222
#define IDS_MSG_DATADIR_IMPORTS						223
#define IDS_MSG_DATADIR_RESOURCES					224
#define IDS_MSG_DATADIR_EXCEPTIONS					225
#define IDS_MSG_DATADIR_SECURITY					226
#define IDS_MSG_DATADIR_RELOCATION_TABLE			227
#define IDS_MSG_DATADIR_DEBUG						228
#define IDS_MSG_DATADIR_ARCHITECTURE				229
#define IDS_MSG_DATADIR_GLOBAL_PTR					230
#define IDS_MSG_DATADIR_TLS							231
#define IDS_MSG_DATADIR_LOAD_CFG					232
#define IDS_MSG_DATADIR_BOUND_IMPORT				233
#define IDS_MSG_DATADIR_IAT							234
#define IDS_MSG_DATADIR_DELAY_LOAD_IMPORT			235
#define IDS_MSG_DATADIR_DOTNET						236
#define IDS_MSG_DATADIR_RESERVED					237
#define IDS_MSG_DATADIR_EXTRA						238

#define IDS_MSG_COMPLETED_DATA						278
#define IDS_MSG_COMPLETED							279
#define IDS_TARGET_FILE_NAME						280

#define IDS_EXIT_MESSAGE							281
#define IDS_ERROR_SECTIONS_TOO_MUCH					282
#define IDS_ERROR_CHECKSUM_RECALC_FAILED			283

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        101
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif

